### ISSUE TITLE
value is string but autocomplete is not

### ISSUE THREAD

**Issue by Solobearus** [Tintef/react-google-places-autocomplete#10]
The initial value and the value from the select. is not the same type.
The value that gets selected has all the the adresses values, and puts the description in the input.
But if I want to already choose a adress in the initial value , I have to use a string value.

Which means that in a CRUD application , I would not be able to open a update window and leave the adress as is. I'll have to choose a new value for me to hold all the adresses value(adress_id, description and so on)

**Comment by Tintef** [comment]
@Solobearus Can you provide some sample code of what you are trying to do?

**Comment by kapilaramji** [comment]
To add to this, and extend on what @Solobearus is saying---

**Example**
Value in store is `address = {"id": "7eae6a016a9c6f58e2044573fb8f14227b6e1f96", "terms": [{"value": "New York", "offset": 0}, {"value": "NY", "offset": 10}, {"value": "USA", "offset": 14}], "types": ["locality", "political", "geocode"], "place_id": "ChIJOwg_06VPwokRYv534QaPC8g", "reference": "ChIJOwg_06VPwokRYv534QaPC8g", "description": "New York, NY, USA", "matched_substrings": [{"length": 3, "offset": 0}], "structured_formatting": {"main_text": "New York", "secondary_text": "NY, USA", "main_text_matched_substrings": [{"length": 3, "offset": 0}]}}`

Current behaviour: `initialValue={address.description}` or whatever we choose

Expected behaviour: `initialValue={address}`

**Comment by Tintef** [comment]
@kapilaramji 

Thas looks reasonable, it would be awesome to support both (current and expected) 🤔

**Comment by kapilaramji** [comment]
@Tintef Yes maybe a solution could be to leave the existing prop as is, and add a new prop for "initialValueObj" based on the Place object.

**Comment by Tintef** [comment]
@kapilaramji 

I think that the best solution is to keep using that prop, but accept `oneOf([string, object])` 🤔

**Comment by Tintef** [comment]
@Solobearus @kapilaramji I'll close this as this is now handled by [react-select](https://react-select.com/) and they provide various ways for handling this scenario

**Comment by usamamashkoor** [comment]
Did you guys find any solution for passing the initial address value?
