### ISSUE TITLE
Unnecessary re-renders triggered whenever click event gets fired 

### ISSUE THREAD

**Issue by bahaa-kallas** [Tintef/react-google-places-autocomplete#109]
While i was investigating some performance issues within my projects I noticed that your component re-render on every click. So I used React profiler and it turns out the `suggestions` state variable keep changing for each click (even outside of the component). I looked into the source and found this:
https://github.com/Tintef/react-google-places-autocomplete/blob/db8e6b4d7f2a4eac1dd7d85d6bb0914e8f68eb2c/src/GooglePlacesAutocomplete/index.js#L55
which apparently used to clear the suggestions when the component lose focus
https://github.com/Tintef/react-google-places-autocomplete/blob/db8e6b4d7f2a4eac1dd7d85d6bb0914e8f68eb2c/src/GooglePlacesAutocomplete/index.js#L90-L96

I think there is another ways to do it than adding event listener on the document level

**Comment by Tintef** [comment]
Hi @bahaa-kallas, thanks for reporting this.

I won't be updating the current code. This is because I'm currently working on a new version of this library that I hope to release in mid-September.

This new version will be written in TypeScript and I'm 99% sure I'll using [react-select](https://react-select.com/). Using this instead of the current input and suggestions list will remove the need to have that event listener.

I'm open to reviewing a PR solving this in the meantime!

**Comment by bahaa-kallas** [comment]
Good to here that. is there a way to get informed when the new library gets published ?

**Comment by Tintef** [comment]
I will close this issue once it gets published, I think you'll get a notification of some sort.

I can also @ you when I close this 😄

**Comment by Tintef** [comment]
@bahaa-kallas FYI, this is already released as an alpha version, you can install it with:

```yarn add react-google-places-autocomplete@3.0.0-alpha.0```

And you can find the new docs [here](https://tintef.github.io/react-google-places-autocomplete/)

**Comment by Tintef** [comment]
@bahaa-kallas This is already merged in master (but still an alpha release), please let me know if this is still an issue on `v3.0.0-alpha.1`
