### ISSUE TITLE
I cannot get the lat and lang of the address. 

### ISSUE THREAD

**Issue by codepurse** [Tintef/react-google-places-autocomplete#117]
Im trying to get the lat and lang of the address using getlatlang but im getting null value instead. Below is my currrent code. 

```
 const [address, setAddress] = useState(null);
  const [coordinates, setCoordinates] = React.useState({
    lat: null,
    lng: null,
  });

  const handleSelect = async (value) => {
    const results = await geocodeByAddress(value);
    const latLng = await getLatLng(results[0]);
    setAddress(value);
    setCoordinates(latLng);
  };


<GooglePlacesAutocomplete
                value={address}
                onChange={setAddress}
                onSelect={handleSelect}
                autocompletionRequest={{
                  componentRestrictions: {
                    country: ["ph"],
                  },
                }}
              />

```

And here's my sample onclick submit

```
 function clickSubmit(e) {
    e.preventDefault();
    $(".pNote").text(coordinates.lat);
  }
```

Any help would be appreciated :)

**Comment by Tintef** [comment]
@codepurse Hi!

Your issue is that `geocodeByAddress` expects a `string` and you are passing the entire object that's returned from Google's API. You should do `geocodeByAddress(value.description)`.

[Here's a working example](https://codesandbox.io/s/practical-bogdan-cnxct)

Also, I noticed you are using a version prior to 3.0.0-alpha, I know it's still in alpha but I'll be releasing 3.0.0 this weekend, so you may want to migrate to this version. [Here's a working example](https://codesandbox.io/s/modern-surf-wt6l2).
