### ISSUE TITLE
Is it possible to pass a value property to the box along with the onChange?

### ISSUE THREAD

**Issue by mendeljacks** [Tintef/react-google-places-autocomplete#126]
I would like to use this component as a controlled component so that when another component updates the address the GooglePlacesAutocomplete can reflect the change.

There seems to be an onSelect property but no value prop?

**Comment by Tintef** [comment]
@mendeljacks In order to use it as a controlled component you need to use it [like this](https://tintef.github.io/react-google-places-autocomplete/docs/examples#controlled-input)

```const [value, setValue] = useState(null);

<GooglePlacesAutocomplete
  selectProps={{
    value,
    onChange: setValue,
  }}
/>```

For more information refer to [react-select documentation](https://react-select.com/) as that's what we are using under the hood to handle the input value.

**Comment by mendeljacks** [comment]
I created a minimum reproducible error. The expected behavior here is that the input box should be initialized with the value 123 Main street, however it initializes with nothing in the box and when the user types nothing gets logged. However when a user selects that part works.
        
<GooglePlacesAutocomplete
            selectProps={{
                value: '123 Main Street',
                onChange: () => {console.log('This should log')},
            }}
            onSelect={({ description }) => (
               console.log(description)
            )}
  />

**Comment by Tintef** [comment]
@mendeljacks For a controlled input value needs to be an object such as `{ label: '123 Main Strret', value: ... }`. If you want to use a string as the initial value you should use the `inputValue` prop as stated on [react-select docs](https://react-select.com/props#statemanager-props) instead of `value`.

`onChange` is called when the user selects an option, not `onSelect` (that's not a prop). If you want to control both the select value **and** the input value you need to do this:

```
import React, { useState } from "react";
import GooglePlacesAutocomplete from "react-google-places-autocomplete";
import "./styles.css";

export default function App() {
  const [inputValue, setInputValue] = useState("");
  const [value, setValue] = useState(null);

  console.log(value);

  return (
    <div className="App">
      <GooglePlacesAutocomplete
        apiKey="YOUR_KEY"
        selectProps={{
          inputValue,
          value,
          onInputChange: (newInputValue, meta) => {
            setInputValue(newInputValue);
          },
          onChange: (newValue, meta) => {
            setValue(newValue);
          }
        }}
      />
    </div>
  );
}
```

Here's a [codesandbox](https://codesandbox.io/s/eloquent-sound-o0wri) as an example, hope this solves your issue.
