### ISSUE TITLE
Please expose session tokens

### ISSUE THREAD

**Issue by natearn** [Tintef/react-google-places-autocomplete#163]
I'm finding that I cannot complete the [session token flow](https://developers.google.com/maps/documentation/javascript/places-autocomplete#session_tokens) with this component as it is now. Specifically, I'm unable to find the session token used in the Places Autocomplete requests without inspecting the network request directly. The same session token needs to be used in a Places Details request, so it would be very helpful if it were exposed somewhere for easy access (such as the results payload in `onChange`).

Additionally, looking through the source code, I was concerned that the session token wouldn't be updating between searches correctly, but what I'm seeing is that there is a new session token being used on every keystroke, which kinda makes the whole thing pointless. If the mistake isn't on my end, then this should be pretty easy to reproduce.

I might not find the time to write a PR for this, but hopefully raising it is helpful. I also rarely report issues, so please forgive any poor etiquette.

**Comment by Tintef** [comment]
@natearn The `sessionToken` is only set when `initializeService` gets called and that only happens when the [component gets mounted](https://github.com/Tintef/react-google-places-autocomplete/blob/master/src/GooglePlacesAutocomplete.tsx#L52).

What I could do is expose a function like `getSessionToken` and you could call it by using a ref to the component 🤔
