### ISSUE TITLE
How to copy paste address using mouse?

### ISSUE THREAD

**Issue by alextaymx** [Tintef/react-google-places-autocomplete#207]
It seems like the component is using react-select, when i right click using mouse or long press in mobile view, i can't paste an address directly into the input field when there is nothing inside, can anyone help me on this? 
Thanks in advance

**Comment by Tintef** [comment]
@alextaymx As you mentioned, that's something on react-select side, so you should go seek help on their repo :)

My guess is that you need to override their components in order to get what you want!

I'm going to close this one out as it's not related to this library, but I hope someone finds this here and helps you out!
