### ISSUE TITLE
Warning: Can't perform a React state update on an unmounted component.

### ISSUE THREAD

**Issue by giacomoalonzi** [Tintef/react-google-places-autocomplete#66]
Hello, I just installed the component and used the basic demo example. 

```
<GooglePlacesAutocomplete apiKey={API_KEY} onSelect={console.log} />
```
I got this

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in GooglePlacesAutocomplete (created by PersonalInfoLocation)
    in div (created by PersonalInfoLocation)
    in PersonalInfoLocation (created by Context.Consumer)
    in Route (created by Onboarding)```

Anyone knows why?

**Comment by Tintef** [comment]
@giacomoalonzi 
Hey, I've never seen this warning while testing the lib.
Can you send more code in order to try to reproduce it? Or even a repository 😄 

Thanks!

**Comment by giacomoalonzi** [comment]
Sorry, the repo is private, the code was the basic one I've written in the previous comment. Nothing special

**Comment by Tintef** [comment]
@giacomoalonzi Can you try creating a minimal reproducible example?
With a fresh react app I'm not able to see this. I would need more insight on what you are doing in order to track down the error.

I suspect that you are briefly mounting the componente and then un-mounting, before the `initalize` function finished (that calls a `setTimeout`).

This might be causing the issue, but I haven't been able to reproduce it yet.
